config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "/", action: :index, controller: :home

  resources :teachers, only: [:index, :show] do
    collection do
      get :search
    end
    resources :ratings, except: :index
  end

  resources :subjects, only: [:index, :show] do
    collection do
      get :search
    end
    resources :ratings, except: :index
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  extend Enumerize

  has_many :users
  has_and_belongs_to_many :subjects

  validates :name, presence: true

  enumerize :area_of_study, in: { biology: 0, humans: 1, exacts: 2}
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :rateable, polymorphic: true
  belongs_to :user

  validates :difficulty, :text, :grade, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  extend Enumerize

  has_many :ratings, as: :rateable
  has_and_belongs_to_many :courses

  validates_presence_of :name, :workload, :description

  enumerize :period, in: { morning: 0, afternoon: 1, night: 2, full_time: 3 }, predicates: true

  scope :last_rated, -> (limit) { joins(:ratings).order("ratings.id DESC").uniq.first(4) }
  scope :search, -> (search) { distinct.joins(:courses).where("subjects.name ILIKE :term OR courses.name ILIKE :term", term: "%#{search}%") }

  def grade
    self.ratings.average(:grade) || 0.0
  end

  def difficulty
    self.ratings.average(:difficulty) || 0.0
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  extend Enumerize

  validates :name, :title, presence: true

  enumerize :title, in: { doctor: 0, master: 1, substitute: 2 }, predicates: true

  has_many :ratings, as: :rateable

  scope :search, -> (search) { distinct.where("name ILIKE :term", term: "%#{search}%") }
  scope :last_rated, -> (limit) { joins(:ratings).order("ratings.id DESC").uniq.first(4) }

  def grade
    self.ratings.average(:grade) || 0.0
  end

  def difficulty
    self.ratings.average(:difficulty) || 0.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :course

  validates_presence_of :name, :email, :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:course_id, :name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @teachers = Teacher.last_rated(4)
    @subjects = Subject.last_rated(4)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :set_rateable, only: [:new, :create, :show]

  def new
    @rating = @rateable.ratings.build
  end

  def create
    @rating      = @rateable.ratings.build rating_params
    @rating.user = current_user

    if @rating.save
      case @rateable.class.to_s
      when 'Teacher'
        redirect_to teacher_path(@rateable)
      when 'Subject'
        redirect_to subject_path(@rateable)
      end
    else
      render 'new'
    end
  end

  def show
    @rating = @rateable.ratings.find_by_id params[:id]
  end

  private

  def set_rateable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return @rateable = $1.classify.constantize.find_by_id(value)
      end
    end
    @rateable = nil
  end

  def rating_params
    params.require(:rating).permit(:difficulty, :to_do, :not_to_do, :text, :take_again, :grade)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.includes(:ratings).order(name: :asc)
  end

  def show
    @subject = Subject.includes(:ratings).find_by_id params[:id]
  end

  def search
    @subjects = Subject.includes(:ratings).search(params[:search]).order(name: :asc)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.includes(:ratings).order(name: :asc)
  end

  def show
    @teacher = Teacher.includes(:ratings).find_by_id params[:id]
  end

  def search
    @teachers = Teacher.includes(:ratings).search(params[:search]).order(name: :asc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def select_course_options
    Course.pluck(:name, :id).unshift(["Escolha seu curso", nil])
  end

  def text_max_length
    250
  end

  def format_date(date)
    date.strftime("%d/%m/%Y")
  end

  def workload_format(workload)
    "#{workload} horas"
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Home</h1>

  <div class="row">
    <h4>Últimos professores avaliados:</h4>

    <div class="row">
      <%= render partial: 'teachers/list' %>
    </div>

    <div class="row">
      <%= link_to 'Ver todos >', teachers_path, class: 'right' %>
    </div>
  </div>

  <div class="row">
    <h4>Últimas disciplinas avaliadas:</h4>

    <div class="row">
      <%= render partial: 'subjects/list' %>
    </div>

    <div class="row">
      <%= link_to 'Ver todos >', subjects_path, class: 'right' %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgwebTrab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body class="blue lighten-5">

    <% unless devise_controller? %>
      <%= render 'shared/navbar' %>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/ratings/new.html.erb
<div class="container">

  <% if @rating.errors.any? %>
    <h4>Errors:</h4>
    <% @rating.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <%= form_for([@rateable, @rating]) do |f| %>
    <div class="row">
      <p class="range-field col s4">
        <%= f.label :difficulty %>
        <%= f.range_field :difficulty, min: 1, max: 5, value: 1 %>
      </p>
    </div>

    <div class="row">
      <p class="range-field col s4">
        <%= f.label :grade %>
        <%= f.range_field :grade, min: 1, max: 5, value: 1 %>
      </p>
    </div>

    <div class="row">
      <div class="switch">
        <label>
          <%= f.label :take_again %>
          <%= f.check_box :take_again %>
          <span class="lever"></span>
        </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s4">
        <i class="material-icons prefix">&#xE145;</i>
        <%= f.label :to_do %>
        <%= f.text_area :to_do, class: 'materialize-textarea', maxlength: text_max_length, data: { length: text_max_length } %>
      </div>

      <div class="input-field col s4">
        <i class="material-icons prefix">&#xE14C;</i>
        <%= f.label :not_to_do %>
        <%= f.text_area :not_to_do, class: 'materialize-textarea', maxlength: text_max_length, data: { length: text_max_length } %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">&#xE150;</i>
        <%= f.label :text %>
        <%= f.text_area :text, class: 'materialize-textarea', maxlength: text_max_length, data: { length: text_max_length } %>
        <p class="observation">Chegou a sua hora de se abrir. Escreva o que está em seu coração, positivo e negativo.</p>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Enviar", class: 'btn' %>
    </div>
  <% end %>

</div>

app/views/ratings/show.html.erb
<div class="container">

  <p>
    <%= link_to :back do %>
      <i class="material-icons">&#xE5C4;</i>
    <% end %>
  </p>

  <div class="row">

    <div class="col s12">
      <div class="card-panel teal">
        <h5 class="white-text">Nota:</h5>
        <p class="white-text"><%= @rating.grade %></p>

        <h5 class="white-text">Dificuldade:</h5>
        <div class="white-text"><%= @rating.difficulty %></div>

        <h5 class="white-text">Avaliação</h5>
        <p class="white-text"><%= @rating.text %></p>

        <h5 class="white-text">Teria aula novamente com esse professor</h5>
        <span class="white-text"><%= (@rating.take_again ? "Sim" : "Não") %></span>

        <h5 class="white-text">Deveria Fazer</h5>
        <p class="white-text"><%= @rating.to_do %></p>

        <h5 class="white-text">Parar de Fazer</h5>
        <p class="white-text"><%= @rating.not_to_do %></p>
      </div>
    </div>

  </div>

</div>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to 'Star Professors', root_path, class: 'brand-logo' %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Disciplinas', subjects_path %></li>
      <li><%= link_to 'Professores', teachers_path %></li>
      <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>

app/views/subjects/_list.html.erb
<% @subjects.each do |subject| %>
  <div class="col s3">
    <div class="card sticky-action">

      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="https://identicon-api.herokuapp.com/<%= subject.name.parameterize %>/300?format=png">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
          <%= subject.name.truncate(20) %>
          <i class="material-icons right">more_vert</i>
        </span>
        <p>Nota: <%= subject.grade.round(2) %></p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">
          <%= subject.name %>
          <i class="material-icons right">close</i>
        </span>
        <p>Nota: <%= subject.grade.round(2) %></p>
        <p>Dificuldade: <%= subject.difficulty.round(2) %></p>
        <p>Total de avaliações: <%= subject.ratings.length %></p>
      </div>

      <div class="card-action center">
        <%= link_to "Detalhes", subject_path(subject) %>
        <%= link_to "Avaliar", new_subject_rating_path(subject) %>
      </div>
    </div>
  </div>
<% end %>

app/views/subjects/index.html.erb
<div class="container">

  <div class="row search-input">
    <%= form_tag(search_subjects_path, remote: true, method: :get) do %>
      <%= text_field_tag :search, params[:search], id: 'subjects_search', placeholder: 'Pesquise uma disciplina aqui' %>
    <% end %>
  </div>

  <div id="subjects_list" class="row">
    <%= render partial: 'list' %>
  </div>

</div>

app/views/subjects/search.js.erb
$("#subjects_list").html("<%= escape_javascript(render('list')) %>");

app/views/subjects/show.html.erb
<div class="container">

  <div class="row">
    <div class="col s4">
      <img width="250" src="https://identicon-api.herokuapp.com/<%= @subject.name.parameterize %>/300?format=png">
    </div>

    <div class="col s8">
      <h3><%= @subject.name %></h3>
      <h5><%= @subject.description %></h5>
      <h5>Carga horária: <%= workload_format @subject.workload %></h5>
      <br>
      <h5>Cursos:</h5>
      <ul class="list">
        <% @subject.courses.each do |course| %>
          <li><%= course.name %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <h5>Nota: <%= @subject.grade.round(2) %></h5>
    <h5>Dificuldade: <%= @subject.difficulty.round(2) %></h5>
  </div>

  <% if @subject.ratings.any? %>

    <div class="row">
      <div class="col s12">
        <%= link_to 'Avaliar', new_subject_rating_path(@subject), class: "btn right" %>
        <h4>Avaliações</h4>
        <p>Total: <%= @subject.ratings.length %></p>
      </div>

      <div class="row">

        <% @subject.ratings.each do |rating| %>
          <div class="col s4">

            <%= link_to subject_rating_path(@subject, rating) do %>
              <div class="card-panel teal">
                <span class="white-text right"><%= format_date(rating.created_at) %></span>
                <p class="white-text">Nota: <%= rating.grade %></p>
                <p class="white-text">Dificuldade: <%= rating.difficulty %></p>
                <p class="white-text">Teria aula novamente: <%= (rating.take_again ? "Sim" : "Não") %></p>
                <p class="white-text truncate">Texto: <%= rating.text %></p>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>

    <% else %>

      <div class="row">
        <div class="center-align col s12">
          <h5>Esse professor ainda não tem avaliações :(</h5>
          <h5>Seja o primeiro a avaliar <%= link_to 'clicando aqui', new_subject_rating_path(@subject) %></h5>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/teachers/_list.html.erb
<% @teachers.each do |teacher| %>
  <div class="col s3">
    <div class="card sticky-action">

      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="<%= teacher.avatar %>">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
          <%= teacher.name.truncate(20) %>
          <i class="material-icons right">more_vert</i>
        </span>
        <p>Nota: <%= teacher.grade.round(2) %></p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">
          <%= teacher.name %>
          <i class="material-icons right">close</i>
        </span>
        <p>Titulo: <%= teacher.title.text %></p>
        <p>Nota: <%= teacher.grade.round(2) %></p>
        <p>Dificuldade: <%= teacher.difficulty.round(2) %></p>
        <p>Total de avaliações: <%= teacher.ratings.length %></p>
      </div>

      <div class="card-action center">
        <%= link_to "Detalhes", teacher_path(teacher) %>
        <%= link_to "Avaliar", new_teacher_rating_path(teacher) %>
      </div>
    </div>
  </div>
<% end %>

app/views/teachers/index.html.erb
<div class="container">

  <div class="row search-input">
    <%= form_tag(search_teachers_path, remote: true, method: :get) do %>
      <%= text_field_tag :search, params[:search], id: 'subjects_search', placeholder: 'Pesquise por um professor aqui' %>
    <% end %>
  </div>

  <div id="teachers_list" class="row">
    <%= render partial: 'list' %>
  </div>

</div>

app/views/teachers/search.js.erb
$("#teachers_list").html("<%= escape_javascript(render('list')) %>");

app/views/teachers/show.html.erb
<div class="container">

  <div class="row">

    <div class="col s4">
      <img class="materialboxed" width="250" src="<%= @teacher.avatar %>">
    </div>

    <div class="col s8">
      <h3><%= @teacher.name %></h3>
      <h4>Título: <%= @teacher.title.text %></h4>

      <h5>Nota: <%= @teacher.grade.round(2) %></h5>
      <h5>Dificuldade: <%= @teacher.difficulty.round(2) %></h5>
    </div>

  </div>

  <% if @teacher.ratings.any? %>

    <div class="row">
      <div class="col s12">
        <%= link_to 'Avaliar', new_teacher_rating_path(@teacher), class: "btn right" %>
        <h4>Avaliações</h4>
        <p>Total: <%= @teacher.ratings.length %></p>
      </div>

      <div class="row">

        <% @teacher.ratings.each do |rating| %>
          <div class="col s4">

            <%= link_to teacher_rating_path(@teacher, rating) do %>
              <div class="card-panel teal">
                <span class="white-text right"><%= format_date(rating.created_at) %></span>
                <p class="white-text">Nota: <%= rating.grade %></p>
                <p class="white-text">Dificuldade: <%= rating.difficulty %></p>
                <p class="white-text">Teria aula novamente: <%= (rating.take_again ? "Sim" : "Não") %></p>
                <p class="white-text truncate">Texto: <%= rating.text %></p>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>

    <% else %>

      <div class="row">
        <div class="center-align col s12">
          <h5>Esse professor ainda não tem avaliações :(</h5>
          <h5>Seja o primeiro a avaliar <%= link_to 'clicando aqui', new_teacher_rating_path(@teacher) %></h5>
        </div>
      </div>

    <% end %>

  </div>
</div>